import React, { useEffect, useState } from "react";
import { Row, Col, Container } from "react-bootstrap";
import columnStyles from "../../styles/SmallMenuContainer.module.css";
import appStyles from "../../App.module.css";
import { useParams } from "react-router";
import { axiosReq } from "../../api/axiosDefaults";
import Post from "./Post";
import CommentCreateForm from "../comments/CommentCreateForm";
import { useCurrentUser } from "../../contexts/CurrentUserContext";
import Comment from "../comments/Comment";
import InfiniteScroll from "react-infinite-scroll-component";
import Asset from "../../components/Asset";
import { fetchMoreData } from "../../utils/utils";
import commentsImage from "../../assets/comment.png";
import LikeFeedAddPost from "../../components/LikeFeedAddPost";
import PopularProfiles from "../profiles/PopularProfiles";